name: Desplegar a cPanel vía FTP

on:
  push:
    branches:
      - master # Usamos master porque tu rama principal se llama así

jobs:
  web-deploy:
    name: Desplegar archivos
    runs-on: ubuntu-latest
    steps:
    - name: Obtener el código
      uses: actions/checkout@v4
      
    - name: Sincronizar con cPanel
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: ./public_html/
